# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Mounts the local "app" directory into the container
    env_file:
      - .env